language: cpp
compiler: gcc
sudo: required

install: 
  - sudo apt update -qq
  # OCLint
  - ./install_oclint.sh

script: 
  - ./build.sh
  - ./do_oclint.sh
  - ./travis_qmake_gcc_cpp11_oclint

after_success:
  - cat oclint.log

after_failure:
  - cat oclint.log
